### PR TITLE
Implemented basic Result features and simple tests

### PR DESCRIPTION
**Pull request by hartmankeaton**
Only one test works due to the status of other classes, the others are there but commented out. Not sure yet if anything else needs to be done for Result but this might be all it needs for the rest of the bits to start working 🤷

### CODE REVIEW

**Comment by hartmankeaton** [comment]
@okonekp  Should I just uncomment the other tests for now since they should be working at some point anyway?

**Comment by okonekp** [comment]
Looks good but dependencies aren't in the main branch yet

**Comment by okonekp** [comment]
Looking over the code again,  there doesn't appear to be a constructor in this class, default or otherwise. It would be good to implement a non-default constructor that fills it with its values instead of needing to create an object with undefined values, then set them all manually.

**Comment by okonekp** [comment]
New tests fit the functionality of the class better, pass, and make sense. Core of the class remains good. This resolves #3. Going to approve merge

**Pull request merged**
