### PR TITLE
Ship implementation

### PR DESCRIPTION
**Pull request by Aidenjn**
includes tests!

### CODE REVIEW

**Comment by hartmankeaton** [comment]
I believe in shipTest()/boardTest() the uses of assert() should instead be assertTrue() to use the jUnit assert function instead of the built-in java function

**Comment by Aidenjn** [comment]
Hi Keaton

**Comment by Aidenjn** [comment]
Commented out bits are unimportant. Don't worry about those.

**Comment by okonekp** [comment]
Assertion changes are resolved in the Board implementation branch and aren't touched here. Though if the code in the comments is unimportant it should just be deleted.

**Comment by Aidenjn** [comment]
Unnecessary comments have been removed. Branch up to date with master and ready to merge

**Pull request merged**
